language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhmv

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - composer update --prefer-source $PREFER_LOWEST
