language: php

sudo: false

matrix:
    include:
        - php: hhvm
        - php: 5.4
        - php: 5.5
        - php: 5.6
          env: deps=low
        - php: 5.6
          env: deps=high
        - php: 7.0
        - php: nightly
    allow_failures:
        - php: nightly
    fast_finish: true

before_install:
    - composer install
